# Generated by Django 4.1.2 on 2022-10-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audio"),
        ),
    ]
