# Generated by Django 4.1.2 on 2022-10-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_audio_post_audio_bytes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="audio_bytes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
