# Generated by Django 4.1.2 on 2022-10-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_audio_bytes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="audio_bytes",
        ),
        migrations.AddField(
            model_name="post",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audio"),
        ),
    ]
